### PR TITLE
Remove hardcoded chainIDs in issue 198

### PR DESCRIPTION
**Pull request by CunliangGeng**
Try to solve #198 .

Updates:
- removed hardcoded chainIDs ('A' and 'B')
- added chainID parameters (chain1 and chain2) for DataGenerator, GridTool,  DataSet and NeuralNet
- updated test code and files (pdb and pssm) 

Requirement:
- pdb2sql > v0.4.0 (e.g. this [commit](https://github.com/DeepRank/pdb2sql/commit/78042230263cda230672ffffa993c8712b12b6a9))

Notice:
- It's not able to use models trained with previous code, because the fixed chain names of mapped features have been changed from `_chainA` and `_chainB` to `_chain1` and `_chain2`, respectively.

### CODE REVIEW

**Comment by CunliangGeng** [comment]
@DarioMarzella Could you have a test on this [branch](https://github.com/DeepRank/deeprank/tree/issue198) ) with your own data to see if the flexible setting of chainIDs works well or not? Check `test_generate.py` and `test_learn.py` for how to set chainIDs.

**Comment by NicoRenaud** [comment]
The code coverage decreased by 20% so I think something is going wrong :)

**Comment by CunliangGeng** [comment]
@NicoRenaud Will have a look at the coverage. I checked the generated hdf5 files which have same values as those generated by former code.

**Comment by CunliangGeng** [comment]
@NicoRenaud The coverage is increased to 77% now. The previous drop is owing to the update of pdb2sql.

**Comment by CunliangGeng** [comment]
The Codacy issues can be ignored. Will merge and close this PR.

**Pull request merged**
